feat(node): test node version

diff --git a/.ansible-ci/files/templated_contexts/node/Dockerfile.j2 b/.ansible-ci/files/templated_contexts/node/Dockerfile.j2
--- a/.ansible-ci/files/templated_contexts/node/Dockerfile.j2
+++ b/.ansible-ci/files/templated_contexts/node/Dockerfile.j2
@@ -22,9 +22,11 @@ ENV CTR_CMD="node" \
 ENV HOME="${CTR_HOME}"
 
 {% if node_version_by_module | default(true) %}
-RUN containeruser-create; ${CTR_PKG_MGM} module enable nodejs:{{ node_version }}; install-pkgs nodejs
+RUN containeruser-create; ${CTR_PKG_MGM} module enable nodejs:{{ node_version }}; install-pkgs nodejs && \
+    [[ "$(node --version | sed 's/^v//')" == "${NODE_VERSION}".* ]] || echo "error: version differs from env var"
 {% else %}
-RUN containeruser-create; install-pkgs nodejs
+RUN containeruser-create; install-pkgs nodejs && \
+    [[ "$(node --version | sed 's/^v//')" == "${NODE_VERSION}"* ]] || echo "error: version differs from env var"
 {% endif %}
 
 USER ${CTR_USER_ID}
